document.write('<header id="secundario">')
document.write('        <nav>')
document.write('            <ul class="list">')
document.write('                <li><a href="/pages/index.html" class="itens" > Início</a></li>')
document.write('                <li><a href="/pages/camisas.html" class="itens" >Camisas</a></li>')
document.write('                <li><a href="/pages/moletons.html" class="itens" >Moletons</a></li>')
document.write('                <li><a href="/pages/calcas.html" class="itens" >Calças</a></li>')
document.write('                <li><a href="/pages/acessorios.html" class="itens">Acessórios</a></li>')
document.write('                <li class="dropdown"><a href="/pages/login.html" class="itens" target="_blank" >Login</a>')
document.write('                    <div class="escondido">')
document.write('                        <a class="itens" href="/pages/cadastro.html">Cadastro</a>')
document.write('                    </div>')
document.write('                </li>')
document.write('            </ul>')
document.write('        </nav>')
document.write('</header>')
